### ISSUE TITLE
Russian Doom\Heretic 5.0 : Midi music is not working.

### ISSUE THREAD

**Issue by Zaratul555** [Russian-Doom/russian-doom#275]
Title says all. Midi option is not working. In Russian Doom 4.7.1 midi is working so its 5.0 bug right?

**Comment by JNechaevsky** [comment]
What is your OS/specs?

**Comment by Zaratul555** [comment]
Windows 10 Pro 64-bit
Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Geforce GTX 970

Btw Crispy Doom and other source ports midi is working.

**Comment by JNechaevsky** [comment]
That's odd, it's working fine on my side. Have you unpacked 5.0 version into 4.x folder, or have you tried a fresh install?

**Comment by Zaratul555** [comment]
I tried both solutions. Its still not working.

**Comment by Zaratul555** [comment]
btw Gus emulation is not working either but i fixed this: 5.0 version does`t have set "gus_patch_path".I added "base\gus_patches\" for that from 4.7.1 and gus music is working. But still no dice for midi music.

**Comment by JNechaevsky** [comment]
Still not sure what is happening. What is full patch of the folder you are running port from?

**Comment by Zaratul555** [comment]
c:\Doom\Source Ports\Russian Doom\

**Comment by JNechaevsky** [comment]
Ah. Could you please temporary rename two folders so they will have spaces? I.e. like this:
```
c:\Doom\Source_Ports\Russian_Doom\
```
And see if it helps?

**Comment by Zaratul555** [comment]
I created folder "c:\Games\Russian_Doom\" and its working! Both Doom and Heretic games have a working midi music. Thanks mate!

**Comment by JNechaevsky** [comment]
Thanks for checking! Guess it's a little-huge problem which should be fixed. Please do not close this ticket until the problem is resolved in the code.

**Comment by Dasperal** [comment]
> btw Gus emulation is not working either but i fixed this: 5.0 version does`t have set "gus_patch_path".I added "base\gus_patches" for that from 4.7.1 and gus music is working. But still no dice for midi music.

Config variable `gus_patch_path` should be an empty string unless you use custom GUS patches. Bundled GUS patches are loaded automatically.

In your case, GUS doesn't work because of spaces in the installation path.

**Comment by Dasperal** [comment]
And we have a big problem here. GUS uses Timidity. The path to GUS patches is written to Timidity config. When Timidity reads its config, it splits lines into words by spaces that result in the segmentation of the path. Quotation marks can't be used to bypass this problem because Timidity reads them as path parts.

Workarounds:
1) Don't use spaces in the installation path.
2) Set config variable `gus_patch_path` or use command line parameter `-gus_patches` with a relative path without spaces from the current directory to the GUS patches directory

**Comment by Dasperal** [comment]
The same problem appears with the `timidity_cfg_path` config variable. Given path is also written to the wrapping Timidity config, so it must not have spaces in it as well.

General MIDI wasn't working because of spaces in the path to russian-midiproc.exe resulted from spaces in the installation path of the Russian Doom. This issue was fixed in adb913b82df590753ef72678c31c0b12c4854b81, b4e46a15fd57671a536765e11fc6080c70824a40 and 3b19f4dfaae7270716bfcb53f725d2fdf99f1230

**Comment by Dasperal** [comment]
The problem in the SDL mixer's Timidity was patched out so now we have to wait for its next release.

For now, I added `BUILD_HAS_SDL_MIXER_PATCH` CMake option which enables usage of the new Timidity config feature on the Russian Doom side. You should build with this option **only** if you are using a modern enough SDL mixer runtime library **with the https://github.com/libsdl-org/SDL_mixer/commit/1c0092787398097360f7da745c7644fd32697f3b patch applied**. Otherwise, GUS emulation and Timidity MIDI **won't work at all**.
